### ISSUE TITLE
Issue on running the code

### ISSUE THREAD

**Issue by Wadha-Almattar** [FDU-VTS/DRTiD#1]
First of all, thanks for sharing the code and the dataset. I faced some issues while running the code.
It's helpful to add a requirement txt file for all packages and libraries that you used in the project. Another important step that I struggled with is where to add the dataset folder?

**Comment by houjunlin** [comment]
Hi, Wadha
Thanks for your suggestion. The requirements.txt file is uploaded for reference, and the dataset can be directly put into the master file. Btw I corrected some code of dataset accessing, so I recommend to redownload the code.

Best

**Comment by YXtrees** [comment]
> 首先，感谢您分享代码和数据集。我在运行代码时遇到了一些问题。为项目中使用的所有包和库添加要求 txt 文件会很有帮助。我努力的另一个重要步骤是在哪里添加 dataset 文件夹？

您好，您添加了什么txt文件，我也遇到了同样的问题

**Comment by YXtrees** [comment]
> 首先，感谢您分享代码和数据集。我在运行代码时遇到了一些问题。为项目中使用的所有包和库添加要求 txt 文件会很有帮助。我努力的另一个重要步骤是在哪里添加 dataset 文件夹？
FileNotFoundError: [Errno 2] No such file or directory: './logs/drtid_single_1.txt'

**Comment by liwenxi** [comment]
> > 首先，感谢您分享代码和数据集。我在运行代码时遇到了一些问题。为项目中使用的所有包和库添加要求 txt 文件会很有帮助。我努力的另一个重要步骤是在哪里添加 dataset 文件夹？
> > FileNotFoundError: [Errno 2] No such file or directory: './logs/drtid_single_1.txt'

I think you can easily solve this problem by using "mkdir logs".

**Comment by YXtrees** [comment]
> > > 首先，感谢您分享代码和数据集。我在运行代码时遇到了一些问题。为项目中使用的所有包和库添加要求 txt 文件会很有帮助。我努力的另一个重要步骤是在哪里添加 dataset 文件夹？
> > > FileNotFoundError: [Errno 2] No such file or directory: './logs/drtid_single_1.txt'
> 
> I think you can easily solve this problem by using "mkdir logs".
感谢您的回复，问题已经解决
